
// This file has been generated by the GUI designer. Do not modify.
namespace hospital_register
{
	public partial class SuccessWindow
	{
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Image image2;
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget hospital_register.SuccessWindow
			this.Name = "hospital_register.SuccessWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("SuccessWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child hospital_register.SuccessWindow.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.fixed2.Add (this.image2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image2]));
			w1.X = 71;
			w1.Y = 65;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("УСПЕШНАЯ ОПЕРАЦИЯ");
			this.fixed2.Add (this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label2]));
			w2.X = 98;
			w2.Y = 64;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 332;
			this.DefaultHeight = 146;
			this.Show ();
		}
	}
}
