
// This file has been generated by the GUI designer. Do not modify.
namespace hospital_register
{
	public partial class EnrollWindow2
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Fixed fixed11;
		private global::Gtk.Label label16;
		private global::Gtk.Image image1;
		private global::Gtk.Image image2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label6;
		private global::Gtk.Label label7;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Notebook notebook2;
		private global::Gtk.TextView textview1;
		private global::Gtk.Label label8;
		private global::Gtk.TextView textview2;
		private global::Gtk.Label label9;
		private global::Gtk.TextView textview3;
		private global::Gtk.Label label10;
		private global::Gtk.TextView textview4;
		private global::Gtk.Label label11;
		private global::Gtk.TextView textview5;
		private global::Gtk.Label label12;
		private global::Gtk.TextView textview6;
		private global::Gtk.Label label13;
		private global::Gtk.Fixed fixed10;
		private global::Gtk.ComboBox combobox2;
		private global::Gtk.Label label15;
		private global::Gtk.Label label14;
		private global::Gtk.Button button1;
		private global::Gtk.ComboBox combobox1;
		private global::Gtk.Calendar calendar1;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Fixed fixed12;
		private global::Gtk.Entry entry1;
		private global::Gtk.Entry entry2;
		private global::Gtk.Label label18;
		private global::Gtk.Label label19;
		private global::Gtk.Button button2;
		private global::Gtk.Label label17;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget hospital_register.EnrollWindow2
			this.Name = "hospital_register.EnrollWindow2";
			this.Title = global::Mono.Unix.Catalog.GetString ("EnrollWindow2");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child hospital_register.EnrollWindow2.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.fixed11 = new global::Gtk.Fixed ();
			this.fixed11.HeightRequest = 100;
			this.fixed11.Name = "fixed11";
			this.fixed11.HasWindow = false;
			// Container child fixed11.Gtk.Fixed+FixedChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("ЗАПИСЬ НА ПРИЕМ");
			this.fixed11.Add (this.label16);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.label16]));
			w1.X = 218;
			w1.Y = 41;
			// Container child fixed11.Gtk.Fixed+FixedChild
			this.image1 = new global::Gtk.Image ();
			this.image1.WidthRequest = 30;
			this.image1.HeightRequest = 30;
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_notes", global::Gtk.IconSize.Menu);
			this.fixed11.Add (this.image1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.image1]));
			w2.X = 181;
			w2.Y = 36;
			// Container child fixed11.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./getClientLogoMini.png"));
			this.fixed11.Add (this.image2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.image2]));
			w3.X = 358;
			w3.Y = 20;
			this.vbox2.Add (this.fixed11);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.fixed11]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.WidthRequest = 361;
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Расписание приемных часов");
			this.hbox2.Add (this.label6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label6]));
			w5.Position = 0;
			w5.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Календарь");
			this.hbox2.Add (this.label7);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label7]));
			w6.Position = 1;
			w6.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 0;
			this.notebook2.BorderWidth = ((uint)(6));
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.notebook2.Add (this.textview1);
			// Notebook tab
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Пн");
			this.notebook2.SetTabLabel (this.textview1, this.label8);
			this.label8.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.textview2 = new global::Gtk.TextView ();
			this.textview2.CanFocus = true;
			this.textview2.Name = "textview2";
			this.notebook2.Add (this.textview2);
			global::Gtk.Notebook.NotebookChild w10 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.textview2]));
			w10.Position = 1;
			// Notebook tab
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Вт");
			this.notebook2.SetTabLabel (this.textview2, this.label9);
			this.label9.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.textview3 = new global::Gtk.TextView ();
			this.textview3.CanFocus = true;
			this.textview3.Name = "textview3";
			this.notebook2.Add (this.textview3);
			global::Gtk.Notebook.NotebookChild w11 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.textview3]));
			w11.Position = 2;
			// Notebook tab
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Ср");
			this.notebook2.SetTabLabel (this.textview3, this.label10);
			this.label10.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.textview4 = new global::Gtk.TextView ();
			this.textview4.CanFocus = true;
			this.textview4.Name = "textview4";
			this.notebook2.Add (this.textview4);
			global::Gtk.Notebook.NotebookChild w12 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.textview4]));
			w12.Position = 3;
			// Notebook tab
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Чт");
			this.notebook2.SetTabLabel (this.textview4, this.label11);
			this.label11.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.textview5 = new global::Gtk.TextView ();
			this.textview5.CanFocus = true;
			this.textview5.Name = "textview5";
			this.notebook2.Add (this.textview5);
			global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.textview5]));
			w13.Position = 4;
			// Notebook tab
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Пт");
			this.notebook2.SetTabLabel (this.textview5, this.label12);
			this.label12.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.textview6 = new global::Gtk.TextView ();
			this.textview6.CanFocus = true;
			this.textview6.Name = "textview6";
			this.notebook2.Add (this.textview6);
			global::Gtk.Notebook.NotebookChild w14 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.textview6]));
			w14.Position = 5;
			// Notebook tab
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Сб");
			this.notebook2.SetTabLabel (this.textview6, this.label13);
			this.label13.ShowAll ();
			this.vbox3.Add (this.notebook2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.notebook2]));
			w15.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed10 = new global::Gtk.Fixed ();
			this.fixed10.WidthRequest = 361;
			this.fixed10.HeightRequest = 97;
			this.fixed10.Name = "fixed10";
			this.fixed10.HasWindow = false;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.combobox2 = global::Gtk.ComboBox.NewText ();
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("хирург"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("офтальмолог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("терапевт"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("гинеколог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("отолоринголог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("кадиолог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("эндокринолог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("аллерголог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("венеролог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("невролог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("рентгенолог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("уролог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("физиотерапевт"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("травматолог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("ревматолог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("околог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("гастероэнтеролог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("дерматолог"));
			this.combobox2.WidthRequest = 127;
			this.combobox2.Name = "combobox2";
			this.fixed10.Add (this.combobox2);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.combobox2]));
			w16.X = 129;
			w16.Y = 63;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Специальность:");
			this.fixed10.Add (this.label15);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.label15]));
			w17.X = 12;
			w17.Y = 70;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Ф.И.О. врача:");
			this.fixed10.Add (this.label14);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.label14]));
			w18.X = 28;
			w18.Y = 25;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Найти");
			this.fixed10.Add (this.button1);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.button1]));
			w19.X = 273;
			w19.Y = 63;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.WidthRequest = 127;
			this.combobox1.Name = "combobox1";
			this.fixed10.Add (this.combobox1);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.combobox1]));
			w20.X = 129;
			w20.Y = 18;
			this.vbox3.Add (this.fixed10);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed10]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.calendar1 = new global::Gtk.Calendar ();
			this.calendar1.CanFocus = true;
			this.calendar1.Name = "calendar1";
			this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox1.Add (this.calendar1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.calendar1]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.fixed12 = new global::Gtk.Fixed ();
			this.fixed12.HeightRequest = 172;
			this.fixed12.Name = "fixed12";
			this.fixed12.HasWindow = false;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.WidthRequest = 90;
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.MaxLength = 4;
			this.entry1.InvisibleChar = '•';
			this.fixed12.Add (this.entry1);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.entry1]));
			w25.X = 272;
			w25.Y = 42;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.WidthRequest = 90;
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.MaxLength = 6;
			this.entry2.InvisibleChar = '•';
			this.fixed12.Add (this.entry2);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.entry2]));
			w26.X = 271;
			w26.Y = 81;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Серия:");
			this.fixed12.Add (this.label18);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.label18]));
			w27.X = 212;
			w27.Y = 43;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Номер:");
			this.fixed12.Add (this.label19);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.label19]));
			w28.X = 207;
			w28.Y = 83;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("ЗАПИСАТЬСЯ");
			this.fixed12.Add (this.button2);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.button2]));
			w29.X = 223;
			w29.Y = 121;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("ПАСПОРТНЫЕ ДАННЫЕ");
			this.fixed12.Add (this.label17);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.label17]));
			w30.X = 208;
			w30.Y = 11;
			this.vbox4.Add (this.fixed12);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.fixed12]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			this.vbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox4]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 575;
			this.DefaultHeight = 497;
			this.Show ();
			this.combobox2.Changed += new global::System.EventHandler (this.OnCombobox2Changed);
		}
	}
}
