
// This file has been generated by the GUI designer. Do not modify.
namespace hospital_register
{
	public partial class AdminWindow
	{
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget hospital_register.AdminWindow
			this.Name = "hospital_register.AdminWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("AdminWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child hospital_register.AdminWindow.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Привет, админ!");
			this.fixed2.Add (this.label2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label2]));
			w1.X = 131;
			w1.Y = 90;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 391;
			this.DefaultHeight = 203;
			this.Show ();
		}
	}
}
