
// This file has been generated by the GUI designer. Do not modify.
namespace hospital_register
{
	public partial class RegisterFailWindow
	{
		private global::Gtk.Fixed fixed3;
		private global::Gtk.Label label2;
		private global::Gtk.Image image4;
		private global::Gtk.Image image3;
		private global::Gtk.Label label3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget hospital_register.RegisterFailWindow
			this.Name = "hospital_register.RegisterFailWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("RegisterFailWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child hospital_register.RegisterFailWindow.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("ОШИБКА РЕГИСТРАЦИИ");
			this.fixed3.Add (this.label2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label2]));
			w1.X = 122;
			w1.Y = 47;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.image4 = new global::Gtk.Image ();
			this.image4.Name = "image4";
			this.image4.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./getClientLogoMini.png"));
			this.fixed3.Add (this.image4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.image4]));
			w2.X = 299;
			w2.Y = 25;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.image3 = new global::Gtk.Image ();
			this.image3.WidthRequest = 30;
			this.image3.HeightRequest = 30;
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-warning", global::Gtk.IconSize.Menu);
			this.fixed3.Add (this.image3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.image3]));
			w3.X = 86;
			w3.Y = 39;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Возможные причины:\n1) Такой пациент уже есть в базе;\n2) Неправильно запеолненный бланк регистрации. \n\nПроверьте правильность заполнения бланка.\nВсе поля должны быть заполнены.");
			this.fixed3.Add (this.label3);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label3]));
			w4.X = 50;
			w4.Y = 87;
			this.Add (this.fixed3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 448;
			this.DefaultHeight = 236;
			this.Show ();
		}
	}
}
