
// This file has been generated by the GUI designer. Do not modify.
namespace hospital_register
{
	public partial class EnrollFailWindow
	{
		private global::Gtk.Fixed fixed4;
		private global::Gtk.Image image5;
		private global::Gtk.Label label4;
		private global::Gtk.Image image6;
		private global::Gtk.Label label5;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget hospital_register.EnrollFailWindow
			this.Name = "hospital_register.EnrollFailWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("EnrollFailWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child hospital_register.EnrollFailWindow.Gtk.Container+ContainerChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.fixed4.Add (this.image5);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.image5]));
			w1.X = 69;
			w1.Y = 107;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("ОШИБКА ЗАПИСИ");
			this.fixed4.Add (this.label4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label4]));
			w2.X = 113;
			w2.Y = 105;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.image6 = new global::Gtk.Image ();
			this.image6.Name = "image6";
			this.image6.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./getClientLogoMini.png"));
			this.fixed4.Add (this.image6);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.image6]));
			w3.X = 248;
			w3.Y = 86;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Проверьте правильность заполнения\n\t\t\tполей для записи");
			this.fixed4.Add (this.label5);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4 [this.label5]));
			w4.X = 61;
			w4.Y = 165;
			this.Add (this.fixed4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 391;
			this.DefaultHeight = 299;
			this.Show ();
		}
	}
}
