
// This file has been generated by the GUI designer. Do not modify.
namespace hospital_register
{
	public partial class RegisterSuccessWindow
	{
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Image image1;
		private global::Gtk.Label label1;
		private global::Gtk.Image image2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget hospital_register.RegisterSuccessWindow
			this.Name = "hospital_register.RegisterSuccessWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("RegisterSuccessWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child hospital_register.RegisterSuccessWindow.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image1 = new global::Gtk.Image ();
			this.image1.WidthRequest = 30;
			this.image1.HeightRequest = 30;
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.fixed2.Add (this.image1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image1]));
			w1.X = 56;
			w1.Y = 81;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Поздравляем с успешной регистрацией \n\t      в поликлинике \"Медстар\"!");
			this.fixed2.Add (this.label1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label1]));
			w2.X = 93;
			w2.Y = 83;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./getClientLogoMini.png"));
			this.fixed2.Add (this.image2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image2]));
			w3.X = 391;
			w3.Y = 71;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 496;
			this.DefaultHeight = 208;
			this.Show ();
		}
	}
}
