
// This file has been generated by the GUI designer. Do not modify.
namespace hospital_register
{
	public partial class TalonWindow
	{
		private global::Gtk.Fixed fixed3;
		private global::Gtk.Label label3;
		private global::Gtk.Image image2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget hospital_register.TalonWindow
			this.Name = "hospital_register.TalonWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("TalonWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child hospital_register.TalonWindow.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("ХВАТАЙ ТАЛОН!");
			this.fixed3.Add (this.label3);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.label3]));
			w1.X = 128;
			w1.Y = 98;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.fixed3.Add (this.image2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3 [this.image2]));
			w2.X = 100;
			w2.Y = 98;
			this.Add (this.fixed3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 386;
			this.DefaultHeight = 231;
			this.Show ();
		}
	}
}
