
// This file has been generated by the GUI designer. Do not modify.
namespace hospital_register
{
	public partial class TalonErrorWindow
	{
		private global::Gtk.Fixed fixed2;
		private global::Gtk.Image image2;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.Image image3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget hospital_register.TalonErrorWindow
			this.Name = "hospital_register.TalonErrorWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("TalonErrorWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child hospital_register.TalonErrorWindow.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.WidthRequest = 30;
			this.image2.HeightRequest = 30;
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.fixed2.Add (this.image2);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image2]));
			w1.X = 71;
			w1.Y = 60;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("ОШИБКА ЗАПИСИ");
			this.fixed2.Add (this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label2]));
			w2.X = 118;
			w2.Y = 67;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Возможные причины:\nтакая запись уже существует");
			this.fixed2.Add (this.label3);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label3]));
			w3.X = 79;
			w3.Y = 112;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.image3 = new global::Gtk.Image ();
			this.image3.Name = "image3";
			this.image3.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./getClientLogoMini.png"));
			this.fixed2.Add (this.image3);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image3]));
			w4.X = 252;
			w4.Y = 44;
			this.Add (this.fixed2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 390;
			this.DefaultHeight = 210;
			this.Show ();
		}
	}
}
