
// This file has been generated by the GUI designer. Do not modify.
namespace hospital_register
{
	public partial class EnrollWindow2
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Fixed fixed11;
		private global::Gtk.Label label16;
		private global::Gtk.Image image1;
		private global::Gtk.Image image2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label6;
		private global::Gtk.Label label7;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Notebook notebook2;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeview1;
		private global::Gtk.Label label8;
		private global::Gtk.Fixed fixed13;
		private global::Gtk.Label label20;
		private global::Gtk.Label label9;
		private global::Gtk.Fixed fixed10;
		private global::Gtk.ComboBox combobox2;
		private global::Gtk.Label label15;
		private global::Gtk.Label label14;
		private global::Gtk.ComboBox combobox1;
		private global::Gtk.Button buttonClear;
		private global::Gtk.Button buttonSearch;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Calendar calendar2;
		private global::Gtk.Fixed fixed14;
		private global::Gtk.Label label21;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Fixed fixed12;
		private global::Gtk.Entry entry1;
		private global::Gtk.Entry entry2;
		private global::Gtk.Label label18;
		private global::Gtk.Label label19;
		private global::Gtk.Button buttonEnroll;
		private global::Gtk.Label label17;
		private global::Gtk.ComboBox combobox3;
		private global::Gtk.Label label22;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget hospital_register.EnrollWindow2
			this.Name = "hospital_register.EnrollWindow2";
			this.Title = global::Mono.Unix.Catalog.GetString ("EnrollWindow2");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child hospital_register.EnrollWindow2.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.fixed11 = new global::Gtk.Fixed ();
			this.fixed11.HeightRequest = 100;
			this.fixed11.Name = "fixed11";
			this.fixed11.HasWindow = false;
			// Container child fixed11.Gtk.Fixed+FixedChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("ЗАПИСЬ НА ПРИЕМ");
			this.fixed11.Add (this.label16);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.label16]));
			w1.X = 218;
			w1.Y = 41;
			// Container child fixed11.Gtk.Fixed+FixedChild
			this.image1 = new global::Gtk.Image ();
			this.image1.WidthRequest = 30;
			this.image1.HeightRequest = 30;
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_notes", global::Gtk.IconSize.Menu);
			this.fixed11.Add (this.image1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.image1]));
			w2.X = 181;
			w2.Y = 36;
			// Container child fixed11.Gtk.Fixed+FixedChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./getClientLogoMini.png"));
			this.fixed11.Add (this.image2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.image2]));
			w3.X = 358;
			w3.Y = 20;
			this.vbox2.Add (this.fixed11);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.fixed11]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.WidthRequest = 361;
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Расписание приемных часов");
			this.hbox2.Add (this.label6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label6]));
			w5.Position = 0;
			w5.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Календарь");
			this.hbox2.Add (this.label7);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label7]));
			w6.Position = 1;
			w6.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 0;
			this.notebook2.BorderWidth = ((uint)(6));
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.HeightRequest = 133;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add (this.treeview1);
			this.notebook2.Add (this.GtkScrolledWindow);
			// Notebook tab
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Расписание");
			this.notebook2.SetTabLabel (this.GtkScrolledWindow, this.label8);
			this.label8.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.fixed13 = new global::Gtk.Fixed ();
			this.fixed13.Name = "fixed13";
			this.fixed13.HasWindow = false;
			// Container child fixed13.Gtk.Fixed+FixedChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("За справкой по использованию\nэлектронной регистрации Вы можете \nобратиться к медрегистратору.");
			this.fixed13.Add (this.label20);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed13 [this.label20]));
			w11.X = 37;
			w11.Y = 40;
			this.notebook2.Add (this.fixed13);
			global::Gtk.Notebook.NotebookChild w12 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.fixed13]));
			w12.Position = 1;
			// Notebook tab
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Справка");
			this.notebook2.SetTabLabel (this.fixed13, this.label9);
			this.label9.ShowAll ();
			this.vbox3.Add (this.notebook2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.notebook2]));
			w13.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed10 = new global::Gtk.Fixed ();
			this.fixed10.WidthRequest = 361;
			this.fixed10.HeightRequest = 100;
			this.fixed10.Name = "fixed10";
			this.fixed10.HasWindow = false;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.combobox2 = global::Gtk.ComboBox.NewText ();
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("хирург"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("офтальмолог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("терапевт"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("гинеколог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("отолоринголог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("кадиолог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("эндокринолог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("аллерголог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("венеролог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("невролог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("рентгенолог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("уролог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("физиотерапевт"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("травматолог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("ревматолог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("околог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("гастероэнтеролог"));
			this.combobox2.AppendText (global::Mono.Unix.Catalog.GetString ("дерматолог"));
			this.combobox2.WidthRequest = 127;
			this.combobox2.Name = "combobox2";
			this.fixed10.Add (this.combobox2);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.combobox2]));
			w14.X = 129;
			w14.Y = 63;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Специальность:");
			this.fixed10.Add (this.label15);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.label15]));
			w15.X = 12;
			w15.Y = 70;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Ф.И.О. врача:");
			this.fixed10.Add (this.label14);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.label14]));
			w16.X = 28;
			w16.Y = 25;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.WidthRequest = 127;
			this.combobox1.Name = "combobox1";
			this.fixed10.Add (this.combobox1);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.combobox1]));
			w17.X = 129;
			w17.Y = 18;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.buttonClear = new global::Gtk.Button ();
			this.buttonClear.CanFocus = true;
			this.buttonClear.Name = "buttonClear";
			this.buttonClear.UseUnderline = true;
			this.buttonClear.Label = global::Mono.Unix.Catalog.GetString ("Очистить");
			this.fixed10.Add (this.buttonClear);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.buttonClear]));
			w18.X = 269;
			w18.Y = 64;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.buttonSearch = new global::Gtk.Button ();
			this.buttonSearch.WidthRequest = 78;
			this.buttonSearch.CanFocus = true;
			this.buttonSearch.Name = "buttonSearch";
			this.buttonSearch.UseUnderline = true;
			this.buttonSearch.Label = global::Mono.Unix.Catalog.GetString ("Найти");
			this.fixed10.Add (this.buttonSearch);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.buttonSearch]));
			w19.X = 267;
			w19.Y = 21;
			this.vbox3.Add (this.fixed10);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed10]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.calendar2 = new global::Gtk.Calendar ();
			this.calendar2.CanFocus = true;
			this.calendar2.Name = "calendar2";
			this.calendar2.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox5.Add (this.calendar2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.calendar2]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.fixed14 = new global::Gtk.Fixed ();
			this.fixed14.HeightRequest = 85;
			this.fixed14.Name = "fixed14";
			this.fixed14.HasWindow = false;
			// Container child fixed14.Gtk.Fixed+FixedChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Мы рады, что Вы решили \nобратиться за услугами \nв клинику \"Медстар\"!\nЗдесь Вас всегда ждут  \nтолько лучшие специалисты.");
			this.fixed14.Add (this.label21);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed14 [this.label21]));
			w23.X = 7;
			w23.Y = 14;
			this.vbox5.Add (this.fixed14);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.fixed14]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox1.Add (this.vbox5);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox5]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.fixed12 = new global::Gtk.Fixed ();
			this.fixed12.HeightRequest = 172;
			this.fixed12.Name = "fixed12";
			this.fixed12.HasWindow = false;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.WidthRequest = 90;
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.MaxLength = 4;
			this.entry1.InvisibleChar = '•';
			this.fixed12.Add (this.entry1);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.entry1]));
			w27.X = 272;
			w27.Y = 42;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.WidthRequest = 90;
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.MaxLength = 6;
			this.entry2.InvisibleChar = '•';
			this.fixed12.Add (this.entry2);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.entry2]));
			w28.X = 271;
			w28.Y = 81;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Серия:");
			this.fixed12.Add (this.label18);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.label18]));
			w29.X = 212;
			w29.Y = 43;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Номер:");
			this.fixed12.Add (this.label19);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.label19]));
			w30.X = 207;
			w30.Y = 83;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.buttonEnroll = new global::Gtk.Button ();
			this.buttonEnroll.CanFocus = true;
			this.buttonEnroll.Name = "buttonEnroll";
			this.buttonEnroll.UseUnderline = true;
			this.buttonEnroll.Label = global::Mono.Unix.Catalog.GetString ("ЗАПИСАТЬСЯ");
			this.fixed12.Add (this.buttonEnroll);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.buttonEnroll]));
			w31.X = 223;
			w31.Y = 121;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("ПАСПОРТНЫЕ ДАННЫЕ");
			this.fixed12.Add (this.label17);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.label17]));
			w32.X = 208;
			w32.Y = 11;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.combobox3 = global::Gtk.ComboBox.NewText ();
			this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("Пн"));
			this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("Вт"));
			this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("Ср"));
			this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("Чт"));
			this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("Пт"));
			this.combobox3.AppendText (global::Mono.Unix.Catalog.GetString ("Сб"));
			this.combobox3.Name = "combobox3";
			this.fixed12.Add (this.combobox3);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.combobox3]));
			w33.X = 131;
			w33.Y = 10;
			// Container child fixed12.Gtk.Fixed+FixedChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("День записи:");
			this.fixed12.Add (this.label22);
			global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed12 [this.label22]));
			w34.X = 32;
			w34.Y = 15;
			this.vbox4.Add (this.fixed12);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.fixed12]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox4]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 598;
			this.DefaultHeight = 589;
			this.Show ();
			this.combobox2.Changed += new global::System.EventHandler (this.OnCombobox2Changed);
			this.buttonClear.Clicked += new global::System.EventHandler (this.OnButtonClearClicked);
			this.buttonSearch.Clicked += new global::System.EventHandler (this.OnButtonSearchClicked);
			this.buttonEnroll.Clicked += new global::System.EventHandler (this.OnButtonEnrollClicked);
		}
	}
}
